nome=input('digite um funcionario: ')
empresa=input('digite a instituicao: ')
qtde_funcionarios=int(input('quantos funcionarios? '))
mediamensalidade=float(input('digite mensalidade media: '))
print(nome + " trabalha em " + empresa)
print("possui: ", qtde_funcionarios, "fucionarios. ")
print("A média de mensalidade é: ", mediamensalidade)
print('---------------confira os dados-----------------')
print("o tipo de variavel nome é: ", type(nome))
print("o tipo de variavel empresa é: ", type(empresa))
print("o tipo de variavel funcionarios é: ", type(qtde_funcionarios))
print("o tipo de variavel mensalidade é: ", type(mediamensalidade))